### ISSUE TITLE
Allow applying plan without confirmation

### ISSUE THREAD

**Issue by albertwidi** [stripe/pg-schema-diff#133]
Currently, the `pg-schema-diff apply` command requires confirmation to continue the process. For example:

```shell
Use the arrow keys to navigate: ↓ ↑ → ← 
? Apply migration with the following hazards: INDEX_BUILD?: 
  ▸ No
    Yes
```

We want to use the CLI to automatically apply the `plan`, but it is tricky because the `apply` command requires us to input the confirmation. It's impossible to bypass the confirmation from the current code/implementation.

Do you think it makes sense to add such a feature?

**Comment by bplunkett-stripe** [comment]
Yes, so basically a "non-interactive" mode. An alternative is to directly integrate with the go library (i.e., creating a very simple go binary that you call from your system).

I think this is a common enough use case though that we should support it.

**Comment by albertwidi** [comment]
Thank you @bplunkett-stripe 🙏
