### ISSUE TITLE
Support nested directories

### ISSUE THREAD

**Issue by bplunkett-stripe** [stripe/pg-schema-diff#155]
Investigate problem with nested directory schemas not being detected.

[See this issue for details](https://github.com/stripe/pg-schema-diff/issues/154)

**Comment by bheemvennapureddy** [comment]
![Screenshot 2024-11-01 at 7 30 37 AM](https://github.com/user-attachments/assets/7e6e8554-18ae-4db9-96ff-a7e978c36f8f)
this nested structure doesn't work for me still with this input 

```
--schema-dir Database.Postgres/Tables
```

**Comment by Navbryce** [comment]
Try wrapping the directory name in single quotes 'like.this'. It's possible your shell is interpreting the periods as special characters

**Comment by bheemvennapureddy** [comment]
will try that - but if thats the case other schemas should have not worked under Tables those worked the ones under `User-Defined Types` didn't work
