### ISSUE TITLE
mask password for dsn

### ISSUE THREAD

**Issue by bheemvennapureddy** [stripe/pg-schema-diff#160]
mask password in the plan log when logging to the console.

**Comment by Navbryce** [comment]
If you want to mask the password, you should use PGPASSWORD env var like you would for psql, and exclude it from your connection string. This also ensures your command history doesn't log thr password. 

This is the same behavior as psql and any libpq-based tool, https://www.postgresql.org/docs/current/libpq-envars.html

**Comment by bheemvennapureddy** [comment]
that works

**Comment by bheemvennapureddy** [comment]
I run into hba conf issues without passing the password in the connection string any insights you can share ?

**Comment by Navbryce** [comment]
I recommend debugging via psql and then emulating that in pg-schema-diff. If you find a discrepancy between the two, let me know. Not to sure exactly what is causing your issue.
