### ISSUE TITLE
[Question] : Folder structure for tables

### ISSUE THREAD

**Issue by bheemvennapureddy** [stripe/pg-schema-diff#162]
do we need to have the tables in the same sequence as they have dependencies?

**Comment by Navbryce** [comment]
This is a good question. I would try to put dependent SQL in the same file, since ordering of statements will be obvious. Otherwise, I'm thinking we will order alphabetically by file path.

**Comment by Navbryce** [comment]
BLUF: filePaths.sort().join("\n").forEach(runSQL) should run successfully on a fresh database.

**Comment by bheemvennapureddy** [comment]
We in SQL server format doesn't follow any sequence for the tables which are dependent was trying to replicate the same and that didn't work with Postgres. When I appended script000 and sequence in the order they are dependent then that worked. We would like to keep the tables in their own file so that it easy to represent schema for each. Is there any way we can automatically figure out the dependencies and order them accordingly?

**Comment by bheemvennapureddy** [comment]
Like using annotations like below 

````

--> depends: a.sql, b.sql
CREATE TABLE c (
    -- ...
);

````

**Comment by bheemvennapureddy** [comment]
Thoughts on that ? @Navbryce

**Comment by bplunkett-stripe** [comment]
Closing. The PR above details the canonical ordering.
