### ISSUE TITLE
Add support for identity columns

### ISSUE THREAD

**Issue by bheemvennapureddy** [stripe/pg-schema-diff#163]
```
-- Table: dbo.Url

-- DROP TABLE IF EXISTS dbo.Url;

CREATE TABLE dbo."Url"
(
    "URL_KEY" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "DOMAIN" VARCHAR(100) NOT NULL,
    "PATH" VARCHAR(1000) NOT NULL,
    "HASH" VARCHAR(50) UNIQUE
);

CREATE INDEX ix_url_ix_hash
    ON dbo."Url" USING btree ("HASH");
```

creates 

<img width="851" alt="Screenshot 2024-08-29 at 1 20 34 AM" src="https://github.com/user-attachments/assets/dc8f8fd6-c8c3-4c24-83bc-49317f004013">

where as it should create 

```
-- Table: dbo.Url

-- DROP TABLE IF EXISTS dbo."Url";

CREATE TABLE IF NOT EXISTS dbo."Url"
(
    "URL_KEY" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "DOMAIN" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "PATH" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    "HASH" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Url_pkey" PRIMARY KEY ("URL_KEY"),
    CONSTRAINT "Url_HASH_key" UNIQUE ("HASH")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS dbo."Url"
    OWNER to postgres;
-- Index: ix_url_ix_hash

-- DROP INDEX IF EXISTS dbo.ix_url_ix_hash;

CREATE INDEX IF NOT EXISTS ix_url_ix_hash
    ON dbo."Url" USING btree
    ("HASH" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
```

**Comment by Navbryce** [comment]
Generated isn't supported yet but serials and sequences are. I recommend using one of those instead.

**Comment by bheemvennapureddy** [comment]
serials are not recommended by Postgres itself https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial

**Comment by bheemvennapureddy** [comment]
So you recommend using serial over  generated identity?

**Comment by bplunkett-stripe** [comment]
No, I'm just saying more to unblock yourself, it might make sense to use serials instead of generated values until support is added.

**Comment by bheemvennapureddy** [comment]
We will be rolling this app soon so we might start writing data soon as well so changing types again will be a problem

**Comment by bplunkett-stripe** [comment]
A serial column is probably naively coercible to a generated value (worth checking). You would want to start the new generated column at an offset higher than the current value (with a significant buffer to account for a race). 

Alternatively, you could try to wait for me to implement this. Unfortunately, I have pretty limited time and implementing new features is not a top priority.

**Comment by bheemvennapureddy** [comment]
Can you throw some insights for me so I can give it a shot if you are open to accept pull requests ?

**Comment by bplunkett-stripe** [comment]
I can probably knock this out today. Let me try to throw a PR up!

**Comment by bplunkett-stripe** [comment]
PR is ready to go! Probably will get a review on Monday and in some time that day. In in the interim, you can try it out.

**Comment by bheemvennapureddy** [comment]
> PR is ready to go! Probably will get a review on Monday and in some time that day. In in the interim, you can try it out.

that worked 

<img width="654" alt="Screenshot 2024-08-31 at 6 32 05 AM" src="https://github.com/user-attachments/assets/362bc515-0838-4558-8894-a21bc028f0c8">

**Comment by bheemvennapureddy** [comment]
@Navbryce for some reason the identity columns are missing nextval() from information schema rather they take a random id for insert, any insights on this ?

**Comment by bplunkett-stripe** [comment]
I mean is the column created correctly by pg-schema-diff, or does this appear to be a Postgres issue?

**Comment by bheemvennapureddy** [comment]
I don't know whats going wrong - i have created the table and column by pg-schema-diff and the information schema is missing the nextval for that 

<img width="427" alt="Screenshot 2024-10-01 at 9 57 07 PM" src="https://github.com/user-attachments/assets/97b9d8c6-56cf-4eed-bc5b-04268d342537">
<img width="617" alt="Screenshot 2024-10-01 at 9 57 30 PM" src="https://github.com/user-attachments/assets/d8f44f50-5223-4191-93ce-244d59bfff1a">


column default is null for this table

**Comment by bheemvennapureddy** [comment]
<img width="729" alt="Screenshot 2024-10-01 at 10 02 06 PM" src="https://github.com/user-attachments/assets/942b0e2d-f953-44af-8166-eb9c5b49c015">
<img width="607" alt="Screenshot 2024-10-01 at 10 02 14 PM" src="https://github.com/user-attachments/assets/4944b2bd-70f5-4657-9185-06b76d6e5a76">
<img width="1188" alt="Screenshot 2024-10-01 at 10 02 29 PM" src="https://github.com/user-attachments/assets/9cdf1d6c-515f-4a19-b011-c8756fa9f128">

**Comment by bheemvennapureddy** [comment]
Probably looks like the bulk inserts are causing issue with seq falling behind

**Comment by bheemvennapureddy** [comment]
Sorry my bad it was the bulk copy which was causing the issue.

**Comment by bplunkett-stripe** [comment]
No worries! If the generated SQL is correct (schema), then the problem is within the application or Postgres. pg-schema-diff doesn't (directly) affect the actual "data plane" of postgres.
