### ISSUE TITLE
[Question] : Clean up temp databases created on the target server

### ISSUE THREAD

**Issue by bheemvennapureddy** [stripe/pg-schema-diff#177]
**Describe the feature**
if the local instance of Postgres is not available, pg-schema-diff creates a temp database on the target server, how do we clean those databases eventually?

**Motivation*
Replication instance also copies over these databases which looks odd and the on-production having these temp databases looks strange as well 

<img width="550" alt="Screenshot 2024-10-11 at 6 46 19 AM" src="https://github.com/user-attachments/assets/89ad89a7-66a7-4b9e-aad1-f489c1c733af">

**Comment by bplunkett-stripe** [comment]
Good call out! 

pg-schema-diff should clean up for you unless the process does not gracefully exit/error, i.e., the process is hard-killed. This is totally possible if you run it with a high frequency.

[There is a ticket to clean up orphaned temporary databases on an as-needed basis](https://github.com/stripe/pg-schema-diff/issues/41). I could try to prioritize that!

I'm going to close this discussion in favor of the linked ticket.
