### ISSUE TITLE
[BUG] cannot drop column of table because other objects depend on it

### ISSUE THREAD

**Issue by aleclarson** [stripe/pg-schema-diff#181]
**Describe the bug**
The following error occurs when attempting to drop a column that is used by a view.
```
Error: executing migration statement. the database maybe be in a dirty state:
   {ALTER TABLE "public"."person" DROP COLUMN "name" 3s 3s
   [DELETES_DATA: Deletes all values in the column]}:
   ERROR: cannot drop column name of table person because other objects depend on it (SQLSTATE 2BP01)
```

**Expected behavior**
If the DELETES_DATA hazard is allowed, the column should be dropped with `CASCADE`.

**To Reproduce**
1. Start with this SQL:
    ```sql
    CREATE TABLE person (
      id serial PRIMARY KEY,
      name text
    );

    CREATE VIEW person_view AS SELECT name FROM person;
    ```
2. Run the migration:
    ```
    pg-schema-diff apply
    ```
3. Update it to this:
    ```sql
    CREATE TABLE person (
      id serial PRIMARY KEY,
      first_name text,
      last_name text
    );

    CREATE VIEW person_view AS
    SELECT
      first_name,
      last_name
    FROM person;
    ```
4. Run the migration:
    ```
    pg-schema-diff apply
    ```

**Context**
pg-schema-diff version: 5fe8259b82bd784644224a861cce575339a45a59
pg-schema-diff usage: CLI
Postgres version: 14

**Comment by bplunkett-stripe** [comment]
We intentionally do not cascade deletes -- this is to avoid implicit deletes. We want all deletes to be done explicitly, i.e., it's a better behavior to fail loudly then implicitly delete the view. This is really just an unfortunate consequence of views not being supported.

#135
