### ISSUE TITLE
Create way to visualize dependency graph

### ISSUE THREAD

**Issue by bplunkett-stripe** [stripe/pg-schema-diff#38]
Create a way to visualize dependency graph. I think the best way to implement this is just to modify the Graph data structure to output a graph in some sort of standard graph format that can be ingested by a graph visualization tool, e.g. [Graphviz](https://graphviz.org/)

**Comment by kevinmingtarja** [comment]
Hi, I'd like to take on this ticket.

**Comment by bplunkett-stripe** [comment]
Sweet, that would be great. I think this ticket basically should create some sort of graph encoder for the [Graph struct in this package](https://github.com/stripe/pg-schema-diff/blob/main/internal/graph/graph.go) that encodes the graph into some common file graph format that can be easily interpreted by an external tool like GraphViz.

I'lll leave the choice of graph file format up to you.

Feel free to respond to this ticket with any questions you might have!

**Comment by kevinmingtarja** [comment]
Thanks for the pointers! 

One quick question, when do you think we should generate this graph output? Some options would be:
- on every plan and/or apply cmd
- create a flag to enable/disable creation of the graph output e.g. `--output-graph`

As for the graph format, I'll go with the format that GraphViz accepts, as you recommended, which is `.dot`. [pprof](https://github.com/google/pprof/blob/main/doc/README.md#graphical-reports) also uses the same format.
