### ISSUE TITLE
Connects to `database=postgres` regardless of `PGDATABASE` value

### ISSUE THREAD

**Issue by sveinnfannar** [stripe/pg-schema-diff#78]
Hi, this project looks very promising and by far the simplest one to use I've found. Great work!

I'm using aiven.io for postgres hosting and AFIK they don't grant access to the default `postgres` database.
S when I run pg-schema-diff I get the following error: `server error (FATAL: database "postgres" does not exist (SQLSTATE 3D000))`

I've tried setting database in the DSN and the `PGDATABASE` env, but with no luck.

**Comment by bplunkett-stripe** [comment]
I'm going to close this because it's stale!
